import Head from 'next/head'

import { getSession, useSession, signOut } from "next-auth/react"

export default function ProfilePage() {
  const { data: session } = useSession()

  const handleSignOut = () => {
    signOut()
  }

  return (
    <div className="container">
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { session && (
        <main className="container mx-auto text-center py-20">
          <h1 className="header">
            <span>User Profile</span>
          </h1>

          <div className="details">
            <h5>{ session.user.name }</h5>
            <p>{ session.user.email }</p>
          </div>

          <div className="mt-6 flex justify-center">
            <a onClick={handleSignOut} className="btn">Log out</a>
          </div>
        </main>
      )}
    </div>
  )
}

export async function getServerSideProps({ req }){
  const session = await getSession({ req })

  if( !session ){
    return{
      redirect:{
        destination: '/auth/login',
        permanent: false
      }
    }
  }

  return{
    props:{
      session
    }
  }
}